//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputSystem/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""cf7e3f52-8638-4e2f-9e8d-4205eb35bd44"",
            ""actions"": [
                {
                    ""name"": ""SelectSkill1"",
                    ""type"": ""Button"",
                    ""id"": ""67dd1198-1a29-4b4a-bf8b-48c3d2746d71"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectSkill2"",
                    ""type"": ""Button"",
                    ""id"": ""16e63e1a-a6bf-4c2a-9353-5c0f70debad9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectSkill3"",
                    ""type"": ""Button"",
                    ""id"": ""9b545a49-9875-445b-9f3a-fd6a12006ab9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectSkill4"",
                    ""type"": ""Button"",
                    ""id"": ""fb562bde-b11b-41a2-b934-242fbbdf471e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectSkill5"",
                    ""type"": ""Button"",
                    ""id"": ""cbfe5eb3-4ff2-4440-8ec8-8766e237bad0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleColorblindMode"",
                    ""type"": ""Button"",
                    ""id"": ""ddecfd79-2d54-4217-8cc8-3c8c9e2a9c06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""81d7cdd1-0bfc-4ee0-a735-f29c517d61df"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectSkill1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39e66fb6-cd37-423a-8f21-316fd236417e"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectSkill2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7dc53c74-d360-4427-a121-90ac7630a7c9"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectSkill3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ae9b943-0559-4274-9a4a-a1e3e223f455"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectSkill4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69eea00a-882b-46ba-ba49-7eaa319c971b"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectSkill5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01510936-5447-413a-b171-78994b1a4909"",
                    ""path"": ""<Keyboard>/slash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleColorblindMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_SelectSkill1 = m_Player.FindAction("SelectSkill1", throwIfNotFound: true);
        m_Player_SelectSkill2 = m_Player.FindAction("SelectSkill2", throwIfNotFound: true);
        m_Player_SelectSkill3 = m_Player.FindAction("SelectSkill3", throwIfNotFound: true);
        m_Player_SelectSkill4 = m_Player.FindAction("SelectSkill4", throwIfNotFound: true);
        m_Player_SelectSkill5 = m_Player.FindAction("SelectSkill5", throwIfNotFound: true);
        m_Player_ToggleColorblindMode = m_Player.FindAction("ToggleColorblindMode", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_SelectSkill1;
    private readonly InputAction m_Player_SelectSkill2;
    private readonly InputAction m_Player_SelectSkill3;
    private readonly InputAction m_Player_SelectSkill4;
    private readonly InputAction m_Player_SelectSkill5;
    private readonly InputAction m_Player_ToggleColorblindMode;
    public struct PlayerActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectSkill1 => m_Wrapper.m_Player_SelectSkill1;
        public InputAction @SelectSkill2 => m_Wrapper.m_Player_SelectSkill2;
        public InputAction @SelectSkill3 => m_Wrapper.m_Player_SelectSkill3;
        public InputAction @SelectSkill4 => m_Wrapper.m_Player_SelectSkill4;
        public InputAction @SelectSkill5 => m_Wrapper.m_Player_SelectSkill5;
        public InputAction @ToggleColorblindMode => m_Wrapper.m_Player_ToggleColorblindMode;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @SelectSkill1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectSkill1;
                @SelectSkill1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectSkill1;
                @SelectSkill1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectSkill1;
                @SelectSkill2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectSkill2;
                @SelectSkill2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectSkill2;
                @SelectSkill2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectSkill2;
                @SelectSkill3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectSkill3;
                @SelectSkill3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectSkill3;
                @SelectSkill3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectSkill3;
                @SelectSkill4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectSkill4;
                @SelectSkill4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectSkill4;
                @SelectSkill4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectSkill4;
                @SelectSkill5.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectSkill5;
                @SelectSkill5.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectSkill5;
                @SelectSkill5.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectSkill5;
                @ToggleColorblindMode.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnToggleColorblindMode;
                @ToggleColorblindMode.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnToggleColorblindMode;
                @ToggleColorblindMode.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnToggleColorblindMode;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SelectSkill1.started += instance.OnSelectSkill1;
                @SelectSkill1.performed += instance.OnSelectSkill1;
                @SelectSkill1.canceled += instance.OnSelectSkill1;
                @SelectSkill2.started += instance.OnSelectSkill2;
                @SelectSkill2.performed += instance.OnSelectSkill2;
                @SelectSkill2.canceled += instance.OnSelectSkill2;
                @SelectSkill3.started += instance.OnSelectSkill3;
                @SelectSkill3.performed += instance.OnSelectSkill3;
                @SelectSkill3.canceled += instance.OnSelectSkill3;
                @SelectSkill4.started += instance.OnSelectSkill4;
                @SelectSkill4.performed += instance.OnSelectSkill4;
                @SelectSkill4.canceled += instance.OnSelectSkill4;
                @SelectSkill5.started += instance.OnSelectSkill5;
                @SelectSkill5.performed += instance.OnSelectSkill5;
                @SelectSkill5.canceled += instance.OnSelectSkill5;
                @ToggleColorblindMode.started += instance.OnToggleColorblindMode;
                @ToggleColorblindMode.performed += instance.OnToggleColorblindMode;
                @ToggleColorblindMode.canceled += instance.OnToggleColorblindMode;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnSelectSkill1(InputAction.CallbackContext context);
        void OnSelectSkill2(InputAction.CallbackContext context);
        void OnSelectSkill3(InputAction.CallbackContext context);
        void OnSelectSkill4(InputAction.CallbackContext context);
        void OnSelectSkill5(InputAction.CallbackContext context);
        void OnToggleColorblindMode(InputAction.CallbackContext context);
    }
}
